# Mixture of Linear Regressions

In this note, we will solve the mixture of linear regressions problem using the moment method.

This block contains some $\LaTeX$ macros.
$\newcommand{\E}{\mathbb{E}}$
$\renewcommand{\Re}{\mathbb{R}}$
$\newcommand{\oft}[1]{{^{(#1)}}}$
$\newcommand{\oftt}[2]{{^{(#1)#2}}}$

In [5]:
import util
from util import *
import models
from models.LinearRegressions import LinearRegressionsMixture
import numpy as np
np.set_printoptions(precision=3, suppress=True)
from IPython.display import display, Markdown, Math
from operator import mul
import sympy as sp
sp.init_printing()

Let $w_1, ..., w_K \in \Re^D$ be a set of $K$ regression coefficients. Let $x_1, ..., x_N \in \Re^D$ be a given set of data points and let $y_n = \sum_{k} \delta_k w_k^\top x_n + \epsilon$ be observed responses. Our objective is to recover $(w_k)$.

## Toy Example

Let's construct a toy example for the rest of this document.

In [7]:
K, D = 2, 2
np.random.seed(0)
pis = np.array([0.4, 0.6])
ws = np.array([[0.75, 0.25], [0.4, 0.9]])
model = LinearRegressionsMixture.generate(K, D, betas = ws, weights = pis, cov =  1.0)
print("True parameters:")
print(model.weights)
print(model.betas)
print(model.sigma)

True parameters:
[ 0.4  0.6]
[[ 0.75  0.25]
 [ 0.4   0.9 ]]
[[ 1.  0.]
 [ 0.  1.]]


# Noiseless, Infinite Data Setting

In this scenario, assume that $\epsilon = 0$ and that we observe expected moments of the data. Consider the moments:
\begin{align}
\E[x^\alpha y^b] 
&= \sum_k \pi_k \E[x^\alpha y^b | \delta_k = 1] \\
&= \sum_k \pi_k \E[x^\alpha [w_k^\top x]^b] \\
&= \sum_k \pi_k \E[x^\alpha \sum_{\beta \in p(b)} w_k^\beta x^\beta] \\
&= \sum_{\beta \in p(b)} \E_\pi[w^\beta] \E[x^{\alpha + \beta}],
\end{align}
where $p(b)$ are the $d$-partitions of $b$. Note that $\E[x^{\alpha + \beta}]$ are observable quantities, and thus this simply represents a mixture over the polynomials with terms $w_k^\beta$.

In [31]:
def evaluate_mixture(ws, pis, beta):
    """
    Compute E_\pi[w^beta]
    """
    return sum(pi * util.monomial(w, beta) for w, pi in zip(ws.T, pis))
    
def compute_exact_y_moments(ws, pis, moments_x, alpha, b):
    """
    Compute the exact moments E[x^a y^b] using coefficients ws, pis and moments_x.
    """
    D, K = ws.shape
    ret = 0.
    coeffs = sp.ntheory.multinomial_coefficients(D,b)
    for beta in partitions(D, b):
        ret += coeffs[beta] * evaluate_mixture(ws, pis, beta) * moments_x[tuple_add(alpha, beta)]
    return ret

def describe_moment_polynomial(R, moments_x, moment_y, alpha, b):
    """
    Computes the moment polynomial for E[x^alpha, y^b]
    """
    D = len(R.symbols)
    w = R.symbols
    expr = -moment_y
    coeffs = sp.ntheory.multinomial_coefficients(D,b)
    for beta in partitions(D, b):
        expr += coeffs[beta] * util.monomial(w, beta) * moments_x[tuple_add(alpha, beta)]
    return expr

In [32]:
# Example 
def double_factorial(n): 
    return reduce(mul, xrange(n, 0, -2)) if n > 0 else 1
def gaussian_moments(sigma, d):
    """
    E[x^d] where x is standard gaussian with sigma
    """
    if d == 0: return 1
    elif d % 2 == 0: return double_factorial(d-1) * sigma**d
    else: return 0
def expected_gaussian_moments(sigma, alphas):
    return {alpha : prod(gaussian_moments(sigma, a) for a in alpha) for alpha in alphas}
def expected_uniform_moments(alphas):
    return {alpha : 1. for alpha in alphas}
def expected_moments_y(ws, pis, moments_x, alphabs):
    return {(alpha, b) : compute_exact_y_moments(ws, pis, moments_x, alpha, b) for alpha, b in alphabs}

In [33]:
R, _ = sp.xring(['w%d'%d for d in xrange(D)], sp.RR, sp.grevlex)

deg_b, deg_x = 3, 2
sigma = model.sigma[0,0]
alphas = list(dominated_elements((deg_x for _ in xrange(D))))
alphabs = [(alpha, b) for alpha in alphas for b in xrange(1,deg_b+1)]
alphas_ = list(dominated_elements((deg_x + deg_b for _ in xrange(D))))
moments_x = expected_gaussian_moments(sigma, alphas_)
moments_y = expected_moments_y(ws, pis, moments_x, alphabs)
#display(moments)

In [34]:
display(moments_x)

In [35]:
display(moments_y)

In [36]:
def get_constraint_polynomials(moments_y, moments_x, deg_x, deg_b):
    constrs = []
    for b in xrange(1, deg_b+1):
        for alpha in util.dominated_elements((deg_x for _ in xrange(D))):
            constrs.append( describe_moment_polynomial(R, moments_x, moments_y[(alpha, b)], alpha, b) )
    return constrs

With this machinery, we can compute the moment polynomials required for the moment method magic!

In [37]:
from mompy.core import MomentMatrix
import mompy.solvers as solvers; reload(solvers)
import mompy.extractors as extractors; reload(extractors)

constrs = get_constraint_polynomials(moments_y, moments_x, deg_x, deg_b)
M = MomentMatrix(3, R.symbols, morder='grevlex')
sol = solvers.solve_generalized_mom_coneqp(M, constrs, 3)
display( model.betas)
display(extractors.extract_solutions_lasserre(M, sol['x'], Kmax=2))

display(extractors.extract_solutions_dreesen_proto(M, sol['x'], Kmax=2))


     pcost       dcost       gap    pres   dres
 0:  3.3331e-01 -1.1934e+00  4e+01  4e+00  8e+00
 1:  1.9518e-01 -3.2675e+00  7e+00  8e-01  1e+00
 2:  1.4298e-01 -1.0911e+00  1e+00  1e-01  2e-01
 3:  3.5067e-02 -1.2531e-01  2e-01  1e-02  2e-02
 4:  5.2528e-03 -1.8015e-02  2e-02  9e-04  2e-03
 5:  8.6614e-04 -2.3142e-03  3e-03  9e-05  2e-04
 6:  2.5471e-04 -8.0417e-05  3e-04  9e-07  2e-06
 7:  5.9055e-05  2.3865e-06  6e-05  1e-07  2e-07
 8:  4.0805e-05  2.3551e-05  2e-05  1e-08  2e-08
 9:  3.0154e-05  2.7546e-05  3e-06  1e-09  2e-09
10:  2.9128e-05  2.8320e-05  8e-07  2e-10  3e-10
11:  2.8647e-05  2.8507e-05  1e-07  2e-11  4e-11
12:  2.8587e-05  2.8549e-05  4e-08  4e-12  7e-12
Optimal solution found.


array([[ 0.75,  0.25],
       [ 0.4 ,  0.9 ]])

lost 0.0006874


the next biggest eigenvalue we are losing is 0.000687


In [38]:
display(constrs)

## With real samples

Let's try to solve the problem with generated samples.


In [45]:
def compute_expected_moments(xs, alphas):
    moments = {alpha : 0. for alpha in alphas}
    for alpha in alphas:
        m = monomial(xs.T, alpha)
        moments[alpha] = m if isinstance(m,float) else float(m.mean())
    return moments

def compute_expected_moments_y(ys, xs, alphabs):
    moments = {(alpha, b) : 0. for alpha, b in alphabs}
    for alpha, b in alphabs:
        moments[(alpha,b)] = float((monomial(xs.T, alpha) * ys**b).mean())
    return moments

In [49]:
xs, ys = model.sample(1e6)
moments_x = compute_expected_moments(xs, alphas_)
moments_y = compute_expected_moments_y(ys, xs, alphabs)

In [50]:
from mompy.core import MomentMatrix
import mompy.solvers as solvers; reload(solvers)
import mompy.extractors as extractors; reload(extractors)

constrs_sdp = get_constraint_polynomials(moments_y, moments_x, deg_x, deg_b)
M = MomentMatrix(3, R.symbols, morder='grevlex')
solsdp = solvers.solve_generalized_mom_coneqp(M, constrs_sdp, None)
#sol = solvers.solve_moments_with_convexiterations(M, constrs, 3)
display(model.betas)
display(extractors.extract_solutions_lasserre(M, solsdp['x'], Kmax=2))

display(extractors.extract_solutions_dreesen_proto(M, solsdp['x'], Kmax=2))
sol = extractors.extract_solutions_dreesen_proto(M, solsdp['x'], Kmax=2)
ws_rec = array([sol[sp.symbols('w0')], sol[sp.symbols('w1')]])

     pcost       dcost       gap    pres   dres
 0:  3.3332e-01 -1.1954e+00  4e+01  4e+00  8e+00
 1:  1.9568e-01 -3.2668e+00  7e+00  8e-01  1e+00
 2:  1.4333e-01 -1.0897e+00  1e+00  1e-01  2e-01
 3:  3.5303e-02 -1.2473e-01  2e-01  1e-02  2e-02
 4:  5.4574e-03 -1.7803e-02  2e-02  9e-04  2e-03
 5:  1.0586e-03 -2.1185e-03  3e-03  9e-05  2e-04
 6:  4.4764e-04  1.1334e-04  3e-04  9e-07  2e-06
 7:  2.5168e-04  1.9545e-04  6e-05  1e-07  2e-07
 8:  2.3409e-04  2.1590e-04  2e-05  1e-08  2e-08
 9:  2.2288e-04  2.2004e-04  3e-06  1e-09  2e-09
10:  2.2179e-04  2.2087e-04  9e-07  3e-10  5e-10
11:  2.2127e-04  2.2112e-04  2e-07  4e-11  7e-11
12:  2.2123e-04  2.2117e-04  6e-08  1e-11  2e-11
Optimal solution found.


array([[ 0.75,  0.25],
       [ 0.4 ,  0.9 ]])

lost 0.0081145


the next biggest eigenvalue we are losing is 0.008114


the next biggest eigenvalue we are losing is 0.008114


In [51]:
for c1, c2 in zip(constrs,constrs_sdp):
    display(c1,"vs", c2)

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

'vs'

In [ ]:
import scipy as sc
import numpy.linalg
np.linalg.matrix_rank((M.numeric_instance(solsdp['x'])), 1e-2)

In [ ]:
M.row_monos

In [ ]:
M.numeric_instance(solsdp['x'])

In [ ]:
moments_y

In [ ]:
moments_x_true = expected_gaussian_moments(sigma, alphas_)
moments_y_true = expected_moments_y(ws, pis, moments_x, alphabs)

In [ ]:
for key in moments_y:
    display(key, abs(moments_y[key] - moments_y_true[key]))